### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by chiyasakura** [RimoChan/internet-dataset#5]
您好，
我看到数据有挺多份的，应该是分段压缩了。我想获得一些任意不同网站的网址数据集，第一阶段大概一万条以上就足够了，请问我可以下载哪一部分数据比较合适，还是说要全部下载。

期待您的回复

**Comment by RimoChan** [comment]
3种类数据都包含「不同网站的网址」，但是抽样的方法不1样。你可以直接把3个`.001`都下回去，看看哪个是你想要的。

**Comment by chiyasakura** [comment]
> 3种类数据都包含「不同网站的网址」，但是抽样的方法不1样。你可以直接把3个`.001`都下回去，看看哪个是你想要的。

好的，非常感谢
